version: "3"
services:
  # Metadata database
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=radon
      - POSTGRES_PASSWORD=radon2023
      - POSTGRES_DB=radon_sql
    volumes:
      # Special volume for Postgres DB
      - /home/neo/data/postgres:/var/lib/postgresql/data
    # TODO: remove this port after testing is complete
    ports:
      - "5451:5432"
    networks:
      - radon_network

  # Backend controller, also a Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # TODO: remove this port after testing is complete
    ports:
      - "5450:5000"
    volumes:
      # Docker socket so that the backend can dynamically spawn containers
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres
    networks:
      - radon_network

  # Frontend container
  #  frontend:
  #    build:
  #      context: ./path/to/your/frontend
  #      dockerfile: Dockerfile
  #    ports:
  #      - 5450:3000

  # Pipeline containers will be spawned dynamically, so they are not defined here

networks:
  radon_network:
