version: "3"
services:
  # Backend controller, also a Flask API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - $XDG_RUNTIME_DIR/docker.sock:/var/run/docker.sock

  # Frontend container
  #  frontend:
  #    build:
  #      context: ./path/to/your/frontend
  #      dockerfile: Dockerfile
  #    volumes:
  #      - ./path/to/your/frontend:/app
  #    ports:
  #      - 5451:3000

  # Metadata database
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=radon
      - POSTGRES_PASSWORD=radon2023
      - POSTGRES_DB=radon_sql
    volumes:
      # Special volume for Postgres DB
      # TODO: change the host path after deployment
      - D:/One/AI/Radon2/data/sql:/var/lib/postgresql/data
    # TODO: remove this port after testing is complete
    ports:
      - "5450:5432"

  # Pipeline containers will be spawned dynamically, so they are not defined here

volumes:
  # Shared volume for the FITS files (using file system)
  fits-data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      # TODO: change the host path after deployment
      device: "D:/One/AI/Radon2/data/fits"

#networks:
#  my_network:
